export const foodCategoryType=[
    { value: "", label: "All" },
    { value: "Mao special", label: "Mao special" },
    { value: "Mutton", label: "Mutton" },
    { value: "Paneer", label: "Paneer" },
    { value: "Fish", label: "Fish" },
    { value: "Prawns", label: "Prawns" },
    { value: "Raan", label: "Raan" },
    { value: "Shawarma", label: "Shawarma" },
    { value: "Tandoori special", label: "Tandoori special" },
    { value: "Chicken special", label: "Chicken special" },
    { value: "Chicken main course", label: "Chicken main course" },
    { value: "Mutton main course", label: "Mutton main course" },
    { value: "Biryani rice", label: "Biryani rice" },
    { value: "Eggs", label: "Eggs" },
    { value: "Vegetable India", label: "Vegetable India" },
    { value: "Rotis", label: "Rotis" },
    { value: "Vegetable soup", label: "Vegetable soup" },
    { value: "Vegetable gravy", label: "Vegetable gravy" },
    { value: "Vegetable noodles", label: "Vegetable noodles" },
    { value: "Rice", label: "Rice" },
    { value: "Chinese main course", label: "Chinese main course" },
    { value: "Non-veg soup", label: "Non-veg soup" },
    { value: "Non-veg noodles", label: "Non-veg noodles" },
    { value: "Starters", label: "Starters" },
    { value: "Sea food starter", label: "Sea food starter" },
    { value: "Sea food rice", label: "Mutton" },
    { value: "Sea food main course", label: "Sea food main course" },
    { value: "Desert", label: "Desert" },
    { value: "Party Pack", label: "Party Pack" },
]